### PR TITLE
keep CompleteMultipartUpload alive

### LINKED ISSUE #30: Timeout with CompleteMultipartUpload
in my use case, a CompleteMultipartUpload can take a longer time and some clients timeout before the s3 server respond.

the Amazon S3 services deals with that problem by sending the response Header early and a whitespace character on an interval until the operation finishes, sending the final response or error as the xml body. 

https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html

> Processing of a Complete Multipart Upload request could take several minutes to complete. After Amazon S3 begins processing the request, it sends an HTTP response header that specifies a 200 OK response. While processing is in progress, Amazon S3 periodically sends white space characters to keep the connection from timing out. A request could fail after the initial 200 OK response has been sent. This means that a 200 OK response can contain either a success or an error. If you call the S3 API directly, make sure to design your application to parse the contents of the response and handle it appropriately. If you use AWS SDKs, SDKs handle this condition. The SDKs detect the embedded error and apply error handling per your configuration settings (including automatically retrying the request as appropriate). If the condition persists, the SDKs throws an exception (or, for the SDKs that don't use exceptions, they return the error).

could we implement a similar solution? I experimented with it by editing the generated files in a branch and it works with the client but the solution is not ideal

https://github.com/lperlaki/s3s/tree/complete_multipart_keepalive

### PR DESCRIPTION
**Pull request by lperlaki**
reopen of #31

> changes the response body from the CompleteMultipartUpload Operation to a custom KeepAliveBody that sends a whitespace every 100 milliseconds to keep the request alive

but now with hyper support for trailers

fixes  #30

---

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

### CODE REVIEW

**Comment by Nugine** [comment]
We have a new failure in e2e tests. Maybe a compatibility issue?
```
{
  "name": "aws-sdk-php",
  "function": "uploadPart ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-65f762b387bb0",
    "Object": "obj1"
  },
  "duration": "261",
  "status": "FAIL",
  "error": "Your proposed upload is smaller than the minimum allowed object size."
}
```

File: crates/s3s/src/ops/mod.rs [hunk 1]
```diff
@@ -69,6 +69,17 @@ fn serialize_error(mut e: S3Error) -> S3Result<Response> {
...
+    let status = e.status_code().unwrap_or(StatusCode::INTERNAL_SERVER_ERROR);
+    let mut res = Response::with_status(status);
+    http::set_xml_body_no_decl(&mut res, &e)?;
+    if let Some(headers) = e.take_headers() {
+        res.headers = headers;
+    }
+    drop(e);
+    Ok(res)
+}
+
```
Comment (Nugine) [inline crates/s3s/src/ops/mod.rs]: It can be merged with `serialize_error` by adding an argument like `xml_decl: bool`.

File: crates/s3s/src/ops/generated.rs [hunk 2]
```diff
@@ -552,14 +552,16 @@ impl super::Operation for CompleteMultipartUpload {
...
-        let result = s3.complete_multipart_upload(s3_req).await;
-        let s3_resp = match result {
-            Ok(val) => val,
-            Err(err) => return super::serialize_error(err),
+        let s3 = s3.clone();
+        let fut = async move {
+            let result = s3.complete_multipart_upload(s3_req).await;
+            match result {
+                Ok(s3_resp) => Self::serialize_http(s3_resp.output).unwrap(),
+                Err(err) => super::serialize_error_no_decl(err).unwrap(),
```
Comment (Nugine) [inline crates/s3s/src/ops/generated.rs]: It's better to propagate the errors instead of aborting current task with a confusing panic. We only use panic when severe errors happen.

**Comment by Nugine** [comment]
I'm busy for the next three weeks. I'll look into the e2e test failure after that. Sorry about the delay but finally we will complete.

**Comment by Nugine** [comment]
It seems that we hit a bug in aws-sdk-php.
+ https://github.com/aws/aws-sdk-php/pull/2932

I'll allow the failed test and merge this PR soon.
